### ISSUE TITLE
Deprecate this repo

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-deprecated/purescript-math#34]
CC @thomashoneyman 

This repo's contents were ported to `purescript-numbers` and `purescript-integers`. All core, contrib, web, and node libraries imports and dependencies have been updated to remove this package. Moreover, the upcoming 0.15.0 package set builds without this package. https://github.com/purescript/package-sets/pull/1075

We can now deprecate this repo.

**Comment by thomashoneyman** [comment]
This should be done once PureScript 0.15 launches. We can update the README, move to `purescript-deprecated`, delete all the files, and push to Pursuit.

**Comment by JordanMartinez** [comment]
This is something we can do now.
